### ISSUE TITLE
bases de datos segunda actividad

### ISSUE THREAD

**Issue by josericardo10** [josericardo10/proyectoFentanilo#2]

**Comment by josericardo10** [comment]
INSERT INTO `provincia`(`codigoProvincia`, `nombre`) VALUES ('1910','independencia'),
('2819','Jose Ricardo'),
('3728','san sebastian'),
('4637','geronimo'),
('5546','chiapas'),
('6454','colima'),
('7363','durango'),
(`8272`,`gunajuato`),
(`9181`,`cloro`),
(`1091`,`orellana`);
nota cambiale el nombre a la primera

**Comment by slimesitopro** [comment]
Awebo

**Comment by josericardo10** [comment]
tambien si puedes manda los otros codigo solo esperame

**Comment by josericardo10** [comment]
[INSERT](http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/8.0/en/insert.html) INTO `provincia`(`codigoProvincia`, `nombre`) [VALUES](http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html%23function_values) ('1910','independencia'), ('2819','Jose Ricardo'), ('3728','san sebastian'), ('4637','geronimo'), ('5546','chiapas'), ('6454','colima'), ('7363','durango'), ('8272','gunajuato'), ('9181','cloro'), ('1091','orellana');        este es el codigo correcto

**Comment by josericardo10** [comment]
INSERT INTO `provincia`(`codigoProvincia`, `nombre`) VALUES ('1910','independencia'),
('2819','Jose Ricardo'),
('3728','san sebastian'),
('4637','geronimo'),
('5546','chiapas'),
('6454','colima'),
('7363','durango'),
('8272','gunajuato'),
('9181','cloro'),
('1091','orellana');   
este es el codigo correcto

**Comment by josericardo10** [comment]
![Captura de pantalla 2024-09-02 225047](https://github.com/user-attachments/assets/e7b0525c-a0c5-474c-be8a-8c7ec1cf71bc)

**Comment by josericardo10** [comment]
ares we solo importa este archivo a tu mysql

**Comment by josericardo10** [comment]
Según yo está ya está completa en codigo
