### ISSUE TITLE
Proyecto laberinto 

### ISSUE THREAD

**Issue by josericardo10** [josericardo10/proyectoFentanilo#4]
Coloca los códigos del HTML, css y javascript por persona además de las imágenes usadas en el laberinto

**Comment by slimesitopro** [comment]
:0

**Comment by antonCDN** [comment]
llego su padre hijos de perra

**Comment by slimesitopro** [comment]
Estás pendejos wey

**Comment by Erickvg12** [comment]
:0

**Comment by josericardo10** [comment]
Listo aquí está Erick
